# gazelle:exclude *.hpp

cc_library(
    name = "cc_chan",
    hdrs = ["chan.hpp"],
    copts = ["-std=c++23"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "cc_strutil",
    hdrs = ["strutil.hpp"],
    copts = ["-std=c++23"],
    visibility = ["//visibility:public"],
)
