load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "dataloader",
    srcs = ["dataloader.go"],
    importpath = "github.com/megakuul/cthulhu/shared/dataloader",
    visibility = ["//visibility:public"],
    deps = ["@com_github_spf13_viper//:go_default_library"],
)
